[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

etherscan_api_key = "FQSX86QUTQYPUNG1WJTYBNC665XPTRYD6J"

[rpc_endpoints]
monad_testnet = "https://rpc-testnet.monadinfra.com/"
monad_mainnet = "https://rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.monadscan.com/api" }
monad_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://monadscan.com/api" }
